[workspace]
members = ["error-code", "error-code-derive"]
resolver = "2"


[workspace.dependencies]
error-code = { path = "./error-code" }
error-code-derive = { path = "./error-code-derive" }
anyhow = "1.0.93"
thiserror = "2.0.3"
http = "1.1.0"
